docs:
  - 'packages/docs/**'
  - 'packages/core/**'
  - 'packages/react/**'
  - 'packages/vue/**'
  - 'scripts/docs-gen-examples.mjs'
  - 'typedoc.json'
  - 'package.json'
  - 'pnpm-lock.yaml'
  - 'pnpm-workspace.yaml'
  - 'turbo.json'
  - 'netlify.toml'
  - '.github/workflows/docs-deploy.yml'
  - '.github/path-filters.yml'
