name: Setup
description: Setup pnpm + Node, restore Turbo cache, and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.25.0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: Cache Turbo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ hashFiles('turbo.json') }}-
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
