packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@testing-library/react': ^16.3.0
  '@tailwindcss/vite': ^4.1.18
  '@types/d3-array': ^3.2.2
  '@types/d3-geo': ^3.1.0
  '@types/d3-selection': ^3.0.11
  '@types/d3-scale': ^4.0.9
  '@types/d3-zoom': ^3.0.8
  '@types/geojson': ^7946.0.16
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/topojson-client': ^3.1.5
  '@types/topojson-specification': ^1.0.5
  '@vitejs/plugin-react': ^5.1.0
  '@vitejs/plugin-vue': ^6.0.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  d3-array: ^3.2.4
  d3-geo: ^3.1.1
  d3-scale: ^4.0.2
  d3-selection: ^3.0.0
  d3-zoom: ^3.0.0
  eslint: ^9.39.3
  jsdom: ^27.3.0
  lint-staged: ^16.2.7
  react: ^19.2.0
  react-dom: ^19.2.0
  remark-insert-headings: ^0.0.0
  remark-toc: ^9.0.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.18
  topojson-client: ^3.1.0
  tsdown: 0.19.0
  turbo: ^2.8.10
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  typedoc-plugin-remark: ^2.0.1
  typedoc-plugin-vue: 1.5.1
  typescript: ^5.9.3
  unplugin-vue: ^6.0.1
  vite: ^7.2.7
  vite-tsconfig-paths: ^6.1.1
  vitepress: ^1.6.4
  vitepress-plugin-tabs: ^0.7.3
  vitest: ^4.0.15
  vue: 3.5.25
  vue-tsc: ^3.2.0

catalogMode: prefer

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks

shellEmulator: true
