import { DEFAULT_SCALE, filePath, readJson, SCALES, writeText } from './utils.mjs'

function wrapperContent(jsonFile) {
  return [
    'import type { Topology } from \'topojson-specification\'',
    `import data from './${jsonFile}' with { type: 'json' }`,
    '',
    'const topology = data as unknown as Topology',
    '',
    'export default topology',
  ].join('\n')
}

function scaleExports(baseName, exportName, defaultScale = DEFAULT_SCALE) {
  return [
    `export { default } from './${baseName}-${defaultScale}.js'`,
    '',
    ...SCALES.map((scale) => `export { default as ${exportName}${scale} } from './${baseName}-${scale}.js'`),
  ].join('\n')
}

async function generateWorldCountries() {
  const dir = filePath('src/world/countries')

  for (const scale of SCALES) {
    await writeText(
      `${dir}/countries-${scale}.ts`,
      wrapperContent(`countries-${scale}.json`),
    )
  }

  await writeText(
    `${dir}/index.ts`,
    scaleExports('countries', 'Countries'),
  )
}

async function generateEntityWrappers(rootDir, metadataPath) {
  const entities = await readJson(metadataPath)

  for (const entity of entities) {
    const { defaultScale, exportName, scales, slug } = entity
    const dir = `${rootDir}/${slug}`

    for (const scale of scales) {
      await writeText(
        `${dir}/${slug}-${scale}.ts`,
        wrapperContent(`${slug}-${scale}.json`),
      )
    }

    await writeText(
      `${dir}/index.ts`,
      scaleExports(slug, exportName, defaultScale),
    )
  }
}

async function generateCountriesExports() {
  const countries = await readJson(filePath('src/metadata/countries.json'))
  const lines = [
    '// Generated by scripts/generate-api.mjs.',
    ...countries.map((country) => `export { default as ${country.exportName} } from './countries/${country.slug}/index.js'`),
  ]

  await writeText(filePath('src/countries.ts'), lines.join('\n'))
}

async function generateIndexExports() {
  const continents = await readJson(filePath('src/metadata/continents.json'))
  const lines = [
    'export { default as Countries } from \'./world/countries/index.js\'',
    'export { Countries10m, Countries50m, Countries110m } from \'./world/countries/index.js\'',
    '',
    ...continents.map((continent) => `export { default as ${continent.exportName} } from './continents/${continent.slug}/index.js'`),
    '',
    'export type { Topology } from \'./types.js\'',
  ]

  await writeText(filePath('src/index.ts'), lines.join('\n'))
}

await generateWorldCountries()
await generateEntityWrappers(
  filePath('src/countries'),
  filePath('src/metadata/countries.json'),
)
await generateEntityWrappers(
  filePath('src/continents'),
  filePath('src/metadata/continents.json'),
)
await generateCountriesExports()
await generateIndexExports()
