import { writeFile } from 'node:fs/promises'

import { fileUrl, readJson } from './utils.mjs'

async function write(path, content) {
  await writeFile(path, `${content.trim()}\n`, 'utf8')
}

const countries = await readJson(fileUrl('src/metadata/countries.json').pathname)
const continents = await readJson(fileUrl('src/metadata/continents.json').pathname)

const countryExports = [
  '// Generated by scripts/generate-exports.mjs.',
  ...countries.map((country) => `export { default as ${country.exportName} } from "./countries/${country.slug}";`),
].join('\n')

await write(fileUrl('src/countries.ts').pathname, countryExports)

const indexExports = [
  'export { default as Countries } from "./world/countries";',
  'export { Countries10m, Countries50m, Countries110m } from "./world/countries";',
  '',
  ...continents.map((continent) => `export { default as ${continent.exportName} } from "./continents/${continent.slug}";`),
  '',
  'export type { Topology } from "./types";',
].join('\n')

await write(fileUrl('src/index.ts').pathname, indexExports)
