export { default as Map } from './Map.vue'
export { default as MapFeature } from './MapFeature.vue'
export { default as MapFeatures } from './MapFeatures.vue'
export { default as MapMarker } from './MapMarker.vue'
export { default as MapZoom } from './MapZoom.vue'
